// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbxTPkTWUpf-zXyUNC4pLoiu10NbKSOLA',
    appId: '1:40113724269:web:f3401da3285674407c9864',
    messagingSenderId: '40113724269',
    projectId: 'mountain-77d15',
    authDomain: 'mountain-77d15.firebaseapp.com',
    storageBucket: 'mountain-77d15.firebasestorage.app',
    measurementId: 'G-68HLC30NRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHuFvtQqIc0s7MDilousq3XYk2_sk8K0E',
    appId: '1:40113724269:android:551240c9634295897c9864',
    messagingSenderId: '40113724269',
    projectId: 'mountain-77d15',
    storageBucket: 'mountain-77d15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFTOoLhib-xwduxCIe98HgZFqB-hQWBGw',
    appId: '1:40113724269:ios:a26bda80dd3624d37c9864',
    messagingSenderId: '40113724269',
    projectId: 'mountain-77d15',
    storageBucket: 'mountain-77d15.firebasestorage.app',
    iosBundleId: 'com.mt.mountain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFTOoLhib-xwduxCIe98HgZFqB-hQWBGw',
    appId: '1:40113724269:ios:a26bda80dd3624d37c9864',
    messagingSenderId: '40113724269',
    projectId: 'mountain-77d15',
    storageBucket: 'mountain-77d15.firebasestorage.app',
    iosBundleId: 'com.mt.mountain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbxTPkTWUpf-zXyUNC4pLoiu10NbKSOLA',
    appId: '1:40113724269:web:fbc82897399ce2867c9864',
    messagingSenderId: '40113724269',
    projectId: 'mountain-77d15',
    authDomain: 'mountain-77d15.firebaseapp.com',
    storageBucket: 'mountain-77d15.firebasestorage.app',
    measurementId: 'G-CPPH3J7JCJ',
  );
}
